Adjust the order: add the first folder first, then the files

diff --git a/.github/workflows/deployment.yaml b/.github/workflows/deployment.yaml
--- a/.github/workflows/deployment.yaml
+++ b/.github/workflows/deployment.yaml
@@ -51,7 +51,6 @@ jobs:
           cache-from: type=gha,scope=backend
           cache-to: type=gha,mode=max,scope=backend
 
-  
   # --- BUILD FRONTEND ---
   build-frontend:
     runs-on: ubuntu-latest
@@ -94,7 +93,8 @@ jobs:
     needs: [build-backend, build-frontend]
 
     steps:
-      - name: Establish an SSH connection and deploy
+      # 1. Create a folder, write a .env file, and start the container via SSH
+      - name: Deploy application via SSH
         uses: appleboy/ssh-action@v1.2.0
         with:
           host: ${{ secrets.SERVER_HOST }}
@@ -103,17 +103,43 @@ jobs:
           script_stop: true # Stop the script immediately if a command fails
           envs: ENV_CONTENT
           script: |
-            # 1. Create and go to the project directory
+            # 1. Create a folder if it doesn't already exist
             mkdir -p ~/conduit-container
             cd ~/conduit-container || exit 1
 
-            # 2. Copy the .env file from GitHub secrets to the server
+            # 2. Write a .env file
             echo "$ENV_CONTENT" > .env
+
+      - name: Log Success Message
+        run: echo "The folder was successfully created, and the .env file was successfully added"
+
+      - name: Copy docker-compose.yml and any files via SCP
+        uses: appleboy/scp-action@v0.1.7
+        with:
+          host: ${{ secrets.SERVER_HOST }}
+          username: ${{ secrets.SERVER_USER }}
+          key: ${{ secrets.SERVER_SSH_KEY }}
+          source: "docker-compose.yml, .gitmodules, example.env, .dockerignore, .gitignore"
+          target: "~/conduit-container/"
+
+      - name: Log Success Message
+        run: echo "The files were successfully added"
+
+      - name: Update and restart Docker containers
+        uses: appleboy/ssh-action@v1.2.0
+        with:
+          host: ${{ secrets.SERVER_HOST }}
+          username: ${{ secrets.SERVER_USER }}
+          key: ${{ secrets.SERVER_SSH_KEY }}
+          script_stop: true # Stop the script immediately if a command fails
+          script: |
+            # 1. Go to the project directory
+            cd ~/conduit-container || exit 1
 
             # 3. Log in to GitHub Container Registry
             echo "${{ secrets.CR_PAT || secrets.GITHUB_TOKEN }}" | docker login ${{ env.REGISTRY }} -u ${{ github.actor }} --password-stdin || exit 1
 
-            # 4. Pull the latest images for backend and frontend
+            # Update and Start the Container
             docker compose pull
             docker compose up -d --remove-orphans
             docker image prune -f
