rewrite the deploymen workflows

diff --git a/.github/workflows/deployment.yaml b/.github/workflows/deployment.yaml
--- a/.github/workflows/deployment.yaml
+++ b/.github/workflows/deployment.yaml
@@ -4,14 +4,15 @@ on:
   push:
     branches:
       - main
+      - feature/c-container # only for testing purposes, remove this line in production
 
 env:
-  GH_TOKEN: ${{ github.token }}
-  BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
-  REPO: ${{ github.repository }}
+  REGISTRY: ghcr.io
 
 jobs:
-  build-and-push:
+
+  # --- BUILD Backend---
+  build-backend:
     runs-on: ubuntu-latest
 
     permissions:
@@ -19,75 +20,99 @@ jobs:
       packages: write
 
     steps:
-      # first step is to checkout the repository and its submodules
+      # Check the repository and its submodules
       - name: Check Repository (inc. Submodule)
         uses: actions/checkout@v4
         with:
           submodules: recursive
         
-      # second step is to log in to GitHub Container Registry
+        # This action is necessary for caching to work. 
+      - name: Set up Docker Buildx
+        uses: docker/setup-buildx-action@v3
+
+      # Log in to GitHub Container Registry
       - name: Log in to GitHub Container Registry
-        uses: docker/login-action@v4
+        uses: docker/login-action@v3
         with:
-          registry: ghcr.io
+          registry: ${{ env.REGISTRY }}
           username: ${{ github.actor }}
           password: ${{ secrets.GITHUB_TOKEN }}
 
       # --- BACKEND BUILD ---
-      - name: Build backend (DJANGO) Image and push to GitHub Container Registry
-        uses: docker/build-push-action@v7
+      - name: Build and push backend
+        uses: docker/build-push-action@v6
         with:
           context: ./backend
           file: ./backend/Dockerfile
           push: true
           tags: |
-            ghcr.io/${{ github.repository_owner }}/conduit-backend:latest
-            ghcr.io/${{ github.repository_owner }}/conduit-backend:${{ github.sha }}
+            ${{ env.REGISTRY }}/${{ github.repository_owner }}/conduit-backend:latest
+            ${{ env.REGISTRY }}/${{ github.repository_owner }}/conduit-backend:${{ github.sha }}
+          cache-from: type=gha,scope=backend
+          cache-to: type=gha,mode=max,scope=backend
 
-      # --- FRONTEND BUILD ---
-      - name: Build frontend Image
-        uses: docker/build-push-action@v7
+  
+  # --- BUILD FRONTEND ---
+  build-frontend:
+    runs-on: ubuntu-latest
+    permissions:
+      contents: read
+      packages: write
+
+    steps:
+      - name: Check Repository (inc. Submodule)
+        uses: actions/checkout@v4
+        with:
+          submodules: recursive
+      # This action is necessary for caching to work. 
+      - name: Set up Docker Buildx
+        uses: docker/setup-buildx-action@v3
+
+      - name: Log in to GitHub Container Registry
+        uses: docker/login-action@v3
+        with:
+          registry: ${{ env.REGISTRY }}
+          username: ${{ github.actor }}
+          password: ${{ secrets.GITHUB_TOKEN }}
+
+      # --- Frontend BUILD ---
+      - name: Build and push Frontend
+        uses: docker/build-push-action@v6
         with:
           context: ./frontend
           file: ./frontend/Dockerfile
           push: true
           tags: |
-            ghcr.io/${{ github.repository_owner }}/conduit-frontend:latest
-            ghcr.io/${{ github.repository_owner }}/conduit-frontend:${{ github.sha }}
+            ${{ env.REGISTRY }}/${{ github.repository_owner }}/conduit-frontend:latest
+            ${{ env.REGISTRY }}/${{ github.repository_owner }}/conduit-frontend:${{ github.sha }}
+          cache-from: type=gha,scope=frontend
+          cache-to: type=gha,mode=max,scope=frontend
 
   deploy-to-server:
     runs-on: ubuntu-latest
-    needs: build-and-push
+    needs: [build-backend, build-frontend]
 
     steps:
-      - name: Checkout
-        uses: actions/checkout@v4
-
-      - name: Upload artifacts docker-compose.yaml
-        uses: actions/upload-artifact@v7
-        with:
-          name: deployment-files
-          path: |
-            docker-compose.yaml
-          include-hidden-files: true
-          if-no-files-found: error
-
       - name: Establish an SSH connection and deploy
-        uses: appleboy/ssh-action@v1.0.3
+        uses: appleboy/ssh-action@v1.2.0
         with:
           host: ${{ secrets.SERVER_HOST }}
           username: ${{ secrets.SERVER_USER }}
           key: ${{ secrets.SERVER_SSH_KEY }}
+          script_stop: true # Stop the script immediately if a command fails
           script: |
             # 1. Go to the project directory
-            cd /conduit-container
+            cd /conduit-container || exit 1
 
-            # 2. Update the repository and submodules
-            git pull origin main
-            git submodule update --init --recursive
+            # 2. Copy the .env file from GitHub secrets to the server
+            cat << 'EOF' > .env
+            ${{ secrets.DOT_ENV_FILE }}
+            EOF
 
-            # 3. Rewrite the .env file from the GitHub secret in real time
-            echo "${{ secrets.DOT_ENV_FILE }}" > .env
+            # 3. Log in to GitHub Container Registry
+            echo "${{ secrets.CR_PAT || secrets.GITHUB_TOKEN }}" | docker login ${{ env.REGISTRY }} -u ${{ github.actor }} --password-stdin
 
-            # 4. Run `docker compose up -d --build`
-            docker compose up -d --build
+            # 4. Pull the latest images for backend and frontend
+            docker compose pull
+            docker compose up -d --remove-orphans
+            docker image prune -f
